[project]
name = "youtube-video-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "customtkinter>=5.2.2",
    "pytube>=15.0.0",
    "pytubefix>=10.3.6",
    "requests>=2.32.5",
]
